import blogImage1 from '../../assets/landingPage/Blogs/blogs-1.png';
import blogImage2 from '../../assets/landingPage/Blogs/blogs-2.png';
import blogImage3 from '../../assets/landingPage/Blogs/blogs-3.png';
import { TBlog } from '../../types';
export const blogs: TBlog[] = [
  {
    id: 1,
    image: blogImage1,
    date: '10 Jan 2021',
    views: '5k',
    comments: '90+',
    authorName: 'Arjun Kumar',
    authorRole: 'Senior Photographer',
    description: 'Pretium sapien, egestas tempor, placerat nibh. Egestas gravida quam vitae nulla pharetra.',
  },
  {
    id: 2,
    image: blogImage2,
    date: '10 Jan 2021',
    views: '5k',
    comments: '90+',
    authorName: 'Arjun Kumar',
    authorRole: 'Senior Photographer',
    description: 'Pretium sapien, egestas tempor, placerat nibh. Egestas gravida quam vitae nulla pharetra.',
  },
  {
    id: 3,
    image: blogImage3,
    date: '10 Jan 2021',
    views: '5k',
    comments: '90+',
    authorName: 'Arjun Kumar',
    authorRole: 'Senior Photographer',
    description: 'Pretium sapien, egestas tempor, placerat nibh. Egestas gravida quam vitae nulla pharetra.',
  },
  {
    id: 4,
    image: blogImage1,
    date: '10 Jan 2021',
    views: '5k',
    comments: '90+',
    authorName: 'Arjun Kumar',
    authorRole: 'Senior Photographer',
    description: 'Pretium sapien, egestas tempor, placerat nibh. Egestas gravida quam vitae nulla pharetra.',
  },
  {
    id: 5,
    image: blogImage2,
    date: '10 Jan 2021',
    views: '5k',
    comments: '90+',
    authorName: 'Arjun Kumar',
    authorRole: 'Senior Photographer',
    description: 'Pretium sapien, egestas tempor, placerat nibh. Egestas gravida quam vitae nulla pharetra.',
  },
  {
    id: 6,
    image: blogImage3,
    date: '10 Jan 2021',
    views: '5k',
    comments: '90+',
    authorName: 'Arjun Kumar',
    authorRole: 'Senior Photographer',
    description: 'Pretium sapien, egestas tempor, placerat nibh. Egestas gravida quam vitae nulla pharetra.',
  },
];